import {
  pgTable,
  varchar,
  integer,
  bigint,
  doublePrecision,
  boolean,
  numeric,
  text,
  serial,
  timestamp,
  date,
  jsonb,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";
import { desc } from "drizzle-orm";

export const priceCandles = pgTable(
  "price_candles",
  {
    epic: varchar("epic", { length: 60 }).notNull(),
    resolution: varchar("resolution", { length: 20 }).notNull(),
    ts: bigint("ts", { mode: "number" }).notNull(),
    open: doublePrecision("open").notNull(),
    high: doublePrecision("high").notNull(),
    low: doublePrecision("low").notNull(),
    close: doublePrecision("close").notNull(),
    volume: integer("volume").default(0),
  },
  (table) => [
    primaryKey({ columns: [table.epic, table.resolution, table.ts] }),
    index("idx_price_candles_lookup").on(table.epic, table.resolution, desc(table.ts)),
  ]
);

export const agentBackups = pgTable("agent_backups", {
  id: serial("id").primaryKey(),
  agentId: varchar("agent_id").notNull(),
  backupName: varchar("backup_name"),
  files: jsonb("files").notNull().default("{}"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const agentMemory = pgTable(
  "agent_memory",
  {
    agentId: varchar("agent_id").notNull(),
    entryType: varchar("entry_type").notNull(),
    entryDate: date("entry_date").notNull().default("1970-01-01"),
    content: text("content").notNull().default(""),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    primaryKey({
      columns: [table.agentId, table.entryType, table.entryDate],
    }),
  ]
);

export const agentSubconscious = pgTable("agent_subconscious", {
  id: serial("id").primaryKey(),
  agentId: varchar("agent_id").notNull(),
  category: varchar("category").notNull(),
  key: varchar("key").notNull(),
  value: text("value").notNull().default(""),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const scalperBacktests = pgTable("scalper_backtests", {
  id: serial("id").primaryKey(),
  strategyId: integer("strategy_id"),
  timeframe: varchar("timeframe"),
  candleCount: integer("candle_count"),
  totalTrades: integer("total_trades"),
  winCount: integer("win_count"),
  lossCount: integer("loss_count"),
  winRate: numeric("win_rate"),
  totalPnl: numeric("total_pnl"),
  maxDrawdown: numeric("max_drawdown"),
  sharpeRatio: numeric("sharpe_ratio"),
  avgWin: numeric("avg_win"),
  avgLoss: numeric("avg_loss"),
  trades: jsonb("trades"),
  configSnapshot: jsonb("config_snapshot"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const scalperConfig = pgTable("scalper_config", {
  id: integer("id").primaryKey().default(1),
  enabled: boolean("enabled").default(true),
  budget: numeric("budget").default("50000"),
  maxDrawdown: numeric("max_drawdown").default("2000"),
  maxMarginPct: numeric("max_margin_pct").default("10"),
  breakEvenBuffer: numeric("break_even_buffer").default("1.5"),
  drawdownTripped: boolean("drawdown_tripped").default(false),
  updatedAt: timestamp("updated_at").defaultNow(),
  demoMode: boolean("demo_mode").default(true),
  demoRejectPct: numeric("demo_reject_pct").default("5"),
  demoSlippageMin: numeric("demo_slippage_min").default("0.1"),
  demoSlippageMax: numeric("demo_slippage_max").default("0.5"),
});

export const scalperStrategies = pgTable("scalper_strategies", {
  id: serial("id").primaryKey(),
  instrument: varchar("instrument").notNull(),
  name: varchar("name"),
  direction: varchar("direction").default("BOTH"),
  enabled: boolean("enabled").default(false),
  size: numeric("size").default("1"),
  stopDistance: numeric("stop_distance"),
  limitDistance: numeric("limit_distance"),
  minMomentumPct: numeric("min_momentum_pct").default("0.03"),
  cooldownMs: integer("cooldown_ms").default(6000),
  tickWindow: integer("tick_window").default(15),
  maxOpenPositions: integer("max_open_positions").default(2),
  minSize: numeric("min_size").default("0.5"),
  maxSize: numeric("max_size").default("10"),
  profitTarget: numeric("profit_target").default("0"),
  trailingStop: numeric("trailing_stop").default("0"),
  warmupMs: integer("warmup_ms").default(60000),
  rsiEnabled: boolean("rsi_enabled").default(false),
  rsiPeriod: integer("rsi_period").default(14),
  rsiOverbought: integer("rsi_overbought").default(70),
  rsiOversold: integer("rsi_oversold").default(30),
  emaEnabled: boolean("ema_enabled").default(false),
  emaShort: integer("ema_short").default(9),
  emaLong: integer("ema_long").default(21),
  macdEnabled: boolean("macd_enabled").default(false),
  macdFast: integer("macd_fast").default(12),
  macdSlow: integer("macd_slow").default(26),
  macdSignal: integer("macd_signal").default(9),
  contractSize: numeric("contract_size"),
  dealId: varchar("deal_id"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  timeframe: varchar("timeframe").default("MINUTE"),
  strategyType: varchar("strategy_type").default("scalper"),
  adxEnabled: boolean("adx_enabled").default(false),
  adxPeriod: integer("adx_period").default(14),
  adxThreshold: numeric("adx_threshold").default("25"),
  bollingerEnabled: boolean("bollinger_enabled").default(false),
  bollingerPeriod: integer("bollinger_period").default(20),
  bollingerSd: numeric("bollinger_sd").default("2"),
  stochasticEnabled: boolean("stochastic_enabled").default(false),
  stochasticK: integer("stochastic_k").default(14),
  stochasticD: integer("stochastic_d").default(3),
  stochasticOb: integer("stochastic_ob").default(80),
  stochasticOs: integer("stochastic_os").default(20),
  atrEnabled: boolean("atr_enabled").default(false),
  atrPeriod: integer("atr_period").default(14),
  atrMultiplier: numeric("atr_multiplier").default("2"),
  rocEnabled: boolean("roc_enabled").default(false),
  rocPeriod: integer("roc_period").default(12),
  rocThreshold: numeric("roc_threshold").default("5"),
  cciEnabled: boolean("cci_enabled").default(false),
  cciPeriod: integer("cci_period").default(20),
  cciThreshold: numeric("cci_threshold").default("100"),
  williamsEnabled: boolean("williams_enabled").default(false),
  williamsPeriod: integer("williams_period").default(14),
  keltnerEnabled: boolean("keltner_enabled").default(false),
  keltnerPeriod: integer("keltner_period").default(20),
  keltnerAtrMult: numeric("keltner_atr_mult").default("1.5"),
  ichimokuEnabled: boolean("ichimoku_enabled").default(false),
  ichimokuTenkan: integer("ichimoku_tenkan").default(9),
  ichimokuKijun: integer("ichimoku_kijun").default(26),
  ichimokuSenkou: integer("ichimoku_senkou").default(52),
  parabolicSarEnabled: boolean("parabolic_sar_enabled").default(false),
  sarAccel: numeric("sar_accel").default("0.02"),
  sarMax: numeric("sar_max").default("0.2"),
  aroonEnabled: boolean("aroon_enabled").default(false),
  aroonPeriod: integer("aroon_period").default(25),
  obvEnabled: boolean("obv_enabled").default(false),
  vwapEnabled: boolean("vwap_enabled").default(false),
  zscoreEnabled: boolean("zscore_enabled").default(false),
  zscorePeriod: integer("zscore_period").default(20),
  zscoreThreshold: numeric("zscore_threshold").default("2"),
  fibEnabled: boolean("fib_enabled").default(false),
  fibLookback: integer("fib_lookback").default(50),
  gridLevels: integer("grid_levels").default(5),
  gridSpacing: numeric("grid_spacing").default("0"),
  kellyEnabled: boolean("kelly_enabled").default(false),
  sentimentEnabled: boolean("sentiment_enabled").default(false),
});

export const scalperTrades = pgTable("scalper_trades", {
  id: serial("id").primaryKey(),
  dealId: varchar("deal_id"),
  epic: varchar("epic"),
  direction: varchar("direction"),
  size: numeric("size"),
  entryPrice: numeric("entry_price"),
  exitPrice: numeric("exit_price"),
  pnl: numeric("pnl"),
  type: varchar("type"),
  strategyName: varchar("strategy_name"),
  openedAt: timestamp("opened_at"),
  closedAt: timestamp("closed_at"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const neuralFeedback = pgTable("neural_feedback", {
  id: serial("id").primaryKey(),
  timestamp: timestamp("timestamp", { withTimezone: true }).defaultNow(),
  agentId: varchar("agent_id", { length: 100 }).notNull(),
  featureVector: jsonb("feature_vector").notNull().default("{}"),
  sentiment: varchar("sentiment", { length: 20 }).notNull(),
  sentimentScore: doublePrecision("sentiment_score").default(0),
  brainResponse: jsonb("brain_response").default("{}"),
  rawText: text("raw_text").default(""),
  sessionId: varchar("session_id", { length: 200 }).default(""),
  architecture: jsonb("architecture").default("{}"),
}, (table) => [
  index("idx_neural_feedback_agent").on(table.agentId),
  index("idx_neural_feedback_sentiment").on(table.sentiment),
  index("idx_neural_feedback_timestamp").on(desc(table.timestamp)),
]);
